name: anvil_forge
version: 0.0.1
publish_to: none

environment:
  sdk: ^2.12.0

dev_dependencies:
  lints: ^1.0.1
  chassis_forge: ^1.1.0
  ardour_tech_analysis:
    git: https://github.com/ArdourTech/ardour_tech_analysis.git
